web:
  build: .
  restart: always
  volumes:
    - .:/app/src
  ports:
    - "8000:8000"
  links:
    - mysql
 
mysql:
  image: mysql:latest
  volumes:
    - /var/lib/mysql
  ports:
    - "3306:3306"
  environment:
    MYSQL_ROOT_PASSWORD: myadminpassword