# Generated by Django 2.1.2 on 2018-10-03 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('age', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('title', models.CharField(max_length=50)),
                ('salary', models.FloatField()),
                ('headquarter', models.CharField(max_length=50)),
            ],
        ),
    ]
