# Generated by Django 2.1.2 on 2018-10-04 04:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('age', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('username', models.CharField(default='0', max_length=15)),
                ('password', models.TextField(default='0000000')),
                ('identification', models.CharField(default='0', max_length=12)),
                ('title', models.CharField(max_length=50)),
                ('phone', models.CharField(default='0000000', max_length=10)),
                ('salary', models.FloatField()),
                ('headquarter', models.IntegerField()),
                ('status', models.BooleanField()),
                ('ip', models.CharField(default='0', max_length=15)),
                ('token', models.TextField(default='0')),
                ('operation', models.IntegerField(default=0)),
                ('created_at', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('last_login', models.DateField(default=datetime.date.today, verbose_name='Date')),
            ],
        ),
    ]
